# Gradle
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=1 -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g -Xmx8g -Xms8g
org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.configuration-cache.problems=warn
org.gradle.configureondemand=true
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.caching=true

# Kotlin
kotlin.code.style=official
kotlin.suppressGradlePluginWarnings=NonKmpAgpIsDeprecated
kotlin.incremental.native=true
kotlin.native.binary.smallBinary=true
kotlin.native.ignoreDisabledTargets=true
kotlin.daemon.jvmargs=-Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=1 -XX:ReservedCodeCacheSize=320m -XX:+HeapDumpOnOutOfMemoryError -XX:MaxMetaspaceSize=1g -Xmx8g -Xms8g

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=false
